apiVersion: v1
kind: Service
metadata:
  name: dev-customerName-projectName-backend-service
  namespace: dev-customerName-projectName-backend
spec:
  ports:
    - port: 3333
      targetPort: 3333
  selector:
    app: dev-customerName-projectName-backend
