services:
  adonis:
    container_name: adonis
    image: flapi/customername-projectname-backend:develop
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - '3556:3556'
    depends_on:
      - db_mariadb
      - phpmyadmin
    networks:
      - app-network

  db_mariadb:
    container_name: db_mariadb
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customerName-projectName_develop
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - '3310:3306'
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db_mariadb
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - '7500:80'
    networks:
      - app-network

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    logging:
      driver: 'none' # disable saving logs
    environment:
      - MH_USERNAME=support@develop.flapi.org
      - MH_PASSWORD=fakepassword
    ports:
      - '1025:1025' # smtp server
      - '8025:8025' # web ui
    networks:
      - app-network

networks:
  app-network:

volumes:
  database_data:
  app:
  node_modules:
