apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: staging-customerName-projectName-backend-cert
  namespace: staging-customerName-projectName-backend
spec:
  secretName: staging-customerName-projectName-backend-tls
  dnsNames:
    - staging.example.api.flapi.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
