apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-customerName-projectName-backend-deployment
  namespace: staging-customerName-projectName-backend
  labels:
    app: staging-customerName-projectName-backend
spec:
  selector:
    matchLabels:
      app: staging-customerName-projectName-backend
  template:
    metadata:
      labels:
        app: staging-customerName-projectName-backend
    spec:
      containers:
        - name: prod-customerName-projectName-backend
          image: corentin35/customerName-projectName-backend:staging-${TAG_VERSION}
          imagePullPolicy: Always
          ports:
            - containerPort: 3333
          env:
            - name: PORT
              value: '3333'
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: '300m'
              memory: '400Mi'
            limits:
              cpu: '600m'
              memory: '800Mi'
      imagePullSecrets:
        - name: regcred
