name: Deployment Staging

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup PHP 8.1, extensions PHP and tools for Laravel v8.x.x
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1' # Laravel v8.x.x support version >= 7.3 and <= 8.1
        extensions: bcmath, ctype, fileinfo, json, mbstring, openssl, pdo, tokenizer, xml, mysql
        tools: composer:v2, phpunit

    - name: Install Dependencies
      run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

    - name: Copy .env
      run: cp .env.example .env

    # Set the environment variables

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Run Migrations
      run: php artisan migrate --force

    - name: Run Seeders
      run: php artisan db:seed

    - name: Run Unit Tests and Functional Tests
      run: php artisan test --parallel

    # Deployment chart HELM to Cluster K3s
