name: tests_build_deploy_cluster_staging

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  tests_build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Decode .env.keys file
        run: |
          echo "${{ secrets.ENCRYPTED_ENV_KEYS_ADONISJS }}" | base64 --decode > .env.keys
          
      - name: Install Node.js to specific version LTS and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies for project
        run: npm install

      - name: Lint TypeScript and ESLint for project
        run: npm run lint:ts && npm run lint:eslint

      - name: Setup Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and run with Docker Compose
        run: |
          docker-compose up --build -d

      - name: Check services healthiness
        uses: thegabriele97/dockercompose-health-action@main
        with:
          timeout: '60'
          workdir: '.'

      - name: Japa - Run Unit Tests and Functional Tests
        run: npm run test:all

      - name: Shutdown Docker Compose
        run: |
          docker-compose down

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/staging/Dockerfile
          push: true
          tags: corentin35/kubequest-backend:staging-${{ github.sha }}

      - name: Replace image tag in deployment.yaml for Kubernetes
        run: |
          sed -i 's/\${TAG_VERSION}/'${{ github.sha }}'/g' k8s/staging/deployment.yaml

      - name: Connect to the cluster K3S for deploy
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG }}
        with:
          args: |
            apply -f k8s/staging/namespace.yaml 
            -f k8s/staging/certificate.yaml 
            -f k8s/staging/docker-registry-secret.yaml 
            -f k8s/staging/deployment.yaml 
            -f k8s/staging/ingress.yaml 
            -f k8s/staging/service.yaml
