name: tests_deploy-release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  tests_deploy-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Decode .env.keys file
        run: |
          echo "${{ secrets.ENCRYPTED_ENV_KEYS_ADONISJS }}" | base64 --decode > .env.keys
          
      - name: Install Node.js to specific version LTS and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies for project
        run: npm install

      - name: Lint TypeScript and ESLint for project
        run: npm run lint:ts && npm run lint:eslint

      - name: Setup Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and run with Docker Compose
        run: |
          docker-compose up --build -d

      - name: Check services healthiness
        uses: thegabriele97/dockercompose-health-action@main
        with:
          timeout: '60'
          workdir: '.'

      - name: Japa - Run Unit Tests and Functional Tests
        run: npm run test:all

      - name: Shutdown Docker Compose
        run: |
          docker-compose down

      - name: Deploy PR (main) for new Release
        uses: googleapis/release-please-action@v4
        with:
          release-type: node
          target-branch: main
          config-file: 'release-please-config.json'
          token: ${{ secrets.PAT_TOKEN }}
